### ISSUE TITLE
Host and instance name conflict for advanced jdbc connectors

### ISSUE THREAD

**Issue by slusardi01** [delphix/masking-initializer#4]
Using the initiator in backup mode, the BASE.json file produces unnecessary parameter entries for both HOST and INSTANCE name when backing up a MSSQL advanced connector.

The tool produces a HOST name parameter entry for Oracle advanced connectors in the BASE.json file when they are not needed.

**Comment by bpg130** [comment]
This tool is storing exactly what the masking application is returning through the API. It looks like the masking application is returning unneeded fields and this is a known bug.

**Comment by slusardi01** [comment]
Thank you for the extra information that this is a bug in the masking application/tool, not the API or the initializer.  Is there a bug number for this, so we can look for it on a future product update?

**Comment by slusardi01** [comment]
Do you have a tentative ETA/ rel # of the MI for when you might add the flag to continue ?

**Comment by bpg130** [comment]
Sorry for the confusion above. There are two sets of issues that are being tracked and it looks like GitHub accidentally picked out the wrong issue number.

There already exists a flag (`-i`) that allows the tool to continue running if there are errors in while restoring a database table configuration. 

In terms of your other question about the bug number, this is not something that we normally hand out as we do not have bugs publicly available, nor do we post bug numbers in release notes so there is no real way for it to be tracked if I give you the bug number, unfortunately.

I am going to build in a workaround to this tool so that we can workaround this bug until it is fixed.
